"""Generate the reference parts of docs/cli.md and docs/configuration.md.

The sources of truth are the `loop` argument parser (cli.build_parser) and the pydantic config
schemas (core/config.py, core.records.SamplingConfig). Each doc keeps hand-written prose outside a marked
region; only the region between the markers is rewritten:

    <!-- BEGIN GENERATED by `loop docs-gen`: do not edit by hand -->
    ...
    <!-- END GENERATED -->

`loop docs-gen` writes the files, `loop docs-gen --check` (and tests/unit/test_docs_generated.py) fails
when they are stale.
"""

from __future__ import annotations

import argparse
import re
import types
import typing
from pathlib import Path
from typing import Any, Literal, get_args, get_origin

from pydantic import BaseModel
from pydantic.fields import FieldInfo
from pydantic_core import PydanticUndefined

from ..core.config import REPO_ROOT, ExperimentConfig, MachineProfile, ModelProfile

BEGIN = "<!-- BEGIN GENERATED by `loop docs-gen`: do not edit by hand -->"
END = "<!-- END GENERATED -->"
CLI_DOC = REPO_ROOT / "docs" / "cli.md"
CONFIG_DOC = REPO_ROOT / "docs" / "configuration.md"


_ANGLE = re.compile(r"[\w./*@:-]*<[\w.@ -]+>[\w./*@<>:-]*")


def _code(m: re.Match) -> str:
    token = m.group(0)
    core = token.rstrip(".,;:")
    return f"`{core}`{token[len(core):]}"


def md(text: str) -> str:
    """Make help text safe for markdown: `<placeholders>` outside code spans would be read as
    HTML tags and disappear on rendering, so tokens containing them become code spans."""
    parts = text.split("`")
    for i in range(0, len(parts), 2):  # even parts are outside code spans
        parts[i] = _ANGLE.sub(_code, parts[i])
    return "`".join(parts)


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #


def _subparsers(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    for action in parser._actions:  # argparse keeps subparsers here; there is no public accessor
        if isinstance(action, argparse._SubParsersAction):
            return dict(action.choices)
    return {}


def _arg_rows(sp: argparse.ArgumentParser) -> list[str]:
    rows = []
    for a in sp._actions:
        if isinstance(a, argparse._HelpAction):
            continue
        name = ", ".join(f"`{o}`" for o in a.option_strings) if a.option_strings else f"`{a.metavar or a.dest}`"
        if a.option_strings and a.nargs != 0:
            name += f" `{a.metavar or a.dest.upper()}`" + (" ..." if a.nargs in ("+", "*") or isinstance(a, argparse._AppendAction) else "")
        elif not a.option_strings and a.nargs in ("+", "*"):
            name += " ..."
        required = "yes" if (a.required or not a.option_strings) and a.nargs not in ("?", "*") else ""
        default = ""
        if a.option_strings and a.nargs != 0 and a.default not in (None, [], argparse.SUPPRESS):
            default = f"`{a.default}`"
        choices = " ".join(f"`{c}`" for c in a.choices) if a.choices else ""
        help_ = md(a.help or "").replace("|", "\\|")
        if choices:
            help_ = f"{help_} (one of {choices})"
        rows.append(f"| {name} | {required} | {default} | {help_} |")
    return rows


def render_cli() -> str:
    from ..cli import EXIT_CODES, build_parser

    parser = build_parser()
    subs = _subparsers(parser)
    out = ["## Commands", "", "| Command | Summary |", "|---|---|"]
    for name, sp in subs.items():
        summary = sp.description.split("\n", 1)[0].rstrip(".")
        out.append(f"| [`loop {name}`](#loop-{name}) | {summary} |")
    out += ["", "## Exit codes", "", "| Code | Meaning |", "|---|---|"]
    out += [f"| {code} | {meaning} |" for code, meaning in EXIT_CODES.items()]
    for name, sp in subs.items():
        summary, _, body = sp.description.partition("\n\n")
        usage = " ".join(sp.format_usage().split())[len("usage: "):]
        out += ["", f"### loop {name}", "", summary, "", "```text", usage, "```", ""]
        out += [md(line.rstrip()) for line in body.strip().splitlines()]
        out += ["", "| Argument | Required | Default | Description |", "|---|---|---|---|", *_arg_rows(sp)]
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #


def _is_model(t: Any) -> bool:
    return isinstance(t, type) and issubclass(t, BaseModel)


def _strip_none(t: Any) -> tuple[Any, bool]:
    if get_origin(t) in (typing.Union, types.UnionType):
        args = [a for a in get_args(t) if a is not type(None)]
        if len(args) < len(get_args(t)):
            return (args[0] if len(args) == 1 else typing.Union[tuple(args)]), True
    return t, False


def _type_str(t: Any) -> str:
    t, optional = _strip_none(t)
    origin = get_origin(t)
    if origin is Literal:
        s = " or ".join(f"`{v}`" for v in get_args(t))
    elif origin is list:
        s = f"list of {_type_str(get_args(t)[0])}"
    elif origin is dict:
        s = "mapping"
    elif _is_model(t):
        s = "mapping"
    elif t is Any:
        s = "any"
    else:
        s = getattr(t, "__name__", str(t))
    return f"{s} or null" if optional else s


def _default_str(f: FieldInfo) -> str:
    if f.is_required():
        return "**required**"
    if f.default_factory is not None:
        v = f.default_factory()
        if isinstance(v, BaseModel):
            dumped = {k: x for k, x in v.model_dump().items() if x not in (None, {}, [])}
            return f"`{dumped}`" if dumped else "defaults below"
        return f"`{v}`"
    if f.default is PydanticUndefined or f.default is None:
        return "null"
    if f.default == "":
        return '`""`'
    return f"`{f.default}`"


def _constraints(f: FieldInfo) -> str:
    parts = []
    for m in f.metadata:
        for attr, sym in (("ge", ">="), ("gt", ">"), ("le", "<="), ("lt", "<")):
            v = getattr(m, attr, None)
            if v is not None:
                parts.append(f"{sym} {v}")
    return f" ({', '.join(parts)})" if parts else ""


def _rows(model: type[BaseModel], prefix: str = "") -> list[str]:
    rows = []
    for name, f in model.model_fields.items():
        key = f"{prefix}{name}"
        t, _ = _strip_none(f.annotation)
        desc = md(f.description or "").replace("|", "\\|")
        rows.append(f"| `{key}` | {_type_str(f.annotation)}{_constraints(f)} | {_default_str(f)} | {desc} |")
        if _is_model(t):
            rows += _rows(t, f"{key}.")
        elif get_origin(t) is list and _is_model(get_args(t)[0]):
            rows += _rows(get_args(t)[0], f"{key}[].")
        elif get_origin(t) is dict and len(get_args(t)) == 2 and _is_model(get_args(t)[1]):
            rows += _rows(get_args(t)[1], f"{key}.<name>.")
    return rows


def _table(title: str, model: type[BaseModel], where: str) -> list[str]:
    doc = (model.__doc__ or "").strip().splitlines()[0] if model.__doc__ else ""
    note = "Keys inside an optional block are required only when the block is present."
    return ["", f"### {title}", "", f"{doc} Files: {where}. {note}", "", "| Key | Type | Default | Description |", "|---|---|---|---|", *_rows(model)]


def render_config() -> str:
    out = ["## Reference"]
    out += _table("Experiment", ExperimentConfig, "`experiments/*.yaml`")
    out += _table("Machine profile", MachineProfile, "`configs/machines/examples/*.yaml`, `configs/machines/local/*.yaml`")
    out += _table("Model profile", ModelProfile, "`configs/models/<name>.yaml`")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- #
# Files
# --------------------------------------------------------------------------- #

TARGETS = {CLI_DOC: render_cli, CONFIG_DOC: render_config}


def _splice(text: str, generated: str, path: Path) -> str:
    if BEGIN not in text or END not in text:
        raise ValueError(f"{path} lacks the generated-region markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{BEGIN}\n\n{generated}\n{END}{tail}"


def expected(path: Path) -> str:
    return _splice(path.read_text(), TARGETS[path](), path)


def check_docs() -> list[Path]:
    return [p for p in TARGETS if p.read_text() != expected(p)]


def write_docs() -> list[Path]:
    written = []
    for p in TARGETS:
        new = expected(p)
        if p.read_text() != new:
            p.write_text(new)
            written.append(p)
    return written


def missing_descriptions() -> list[str]:
    """Config fields and CLI arguments without a description (tested: must be empty)."""
    from ..cli import build_parser

    missing: list[str] = []

    def walk(model: type[BaseModel], prefix: str) -> None:
        for name, f in model.model_fields.items():
            if not f.description:
                missing.append(f"config: {prefix}{name}")
            t, _ = _strip_none(f.annotation)
            inner = get_args(t)[-1] if get_origin(t) in (list, dict) and get_args(t) else t
            if _is_model(inner):
                walk(inner, f"{prefix}{name}.")

    for m in (ExperimentConfig, MachineProfile, ModelProfile):
        walk(m, f"{m.__name__}.")
    for name, sp in _subparsers(build_parser()).items():
        if "\n\n" not in (sp.description or ""):
            missing.append(f"cli: loop {name} (description)")
        for a in sp._actions:
            if not isinstance(a, argparse._HelpAction) and not a.help:
                missing.append(f"cli: loop {name} {a.option_strings or a.dest}")
    return missing
